version: "3.5"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: eventifica
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: events 
  neo4j:
    image: neo4j
    ports:
      - 7888:7474
      - 7999:7687
    restart: unless-stopped
    environment:
      - NEO4J-AUTH=eventifica/123
    volumes: 
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
  app:
    build: .
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_NAME: events
      MONGO_USER: eventifica
      MONGO_PASS: 123
      SECRET: 9b9bed51-fddd-424f-8f4a-fcc77593604f
    ports:
      - 3030:3030
    volumes: 
      - .:/usr/app
    links:
      - mongo
      - neo4j
    depends_on:
      - mongo
      - neo4j