version: "3.5"
services:
  database:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: eventifica
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: events 
  app:
    build: .
    environment:
      DB_HOST: database
      DB_PORT: 27017
      DB_NAME: events
      DB_USER: eventifica
      DB_PASS: 123
    ports:
      - 3030:3030
    volumes: 
      - .:/usr/app
    links:
      - database
    depends_on:
      - database